name: Build TV APK

on:
  push:
    branches: [ main ]
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'
      - run: flutter pub get
      - run: flutter build apk --release --flavor tv
      - uses: actions/upload-artifact@v3
        with:
          name: tv-apk
          path: build/app/outputs/flutter-apk/app-release.apk
