name: Build TV APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # 进入 TV 版应用目录
      - name: Navigate to TV app
        run: cd simple_live_tv_app && ls -la
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'
      
      # 在 TV 应用目录下执行 Flutter 命令
      - name: Get dependencies
        run: |
          cd simple_live_tv_app
          flutter pub get
      
      - name: Build APK
        run: |
          cd simple_live_tv_app
          flutter build apk --release
      
      - uses: actions/upload-artifact@v4
        with:
          name: tv-apk
